
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StudentOperationsService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/DVL/student?wsdl")
public class StudentOperationsService
    extends Service
{

    private final static URL STUDENTOPERATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTOPERATIONSSERVICE_EXCEPTION;
    private final static QName STUDENTOPERATIONSSERVICE_QNAME = new QName("http://server/", "StudentOperationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DVL/student?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTOPERATIONSSERVICE_WSDL_LOCATION = url;
        STUDENTOPERATIONSSERVICE_EXCEPTION = e;
    }

    public StudentOperationsService() {
        super(__getWsdlLocation(), STUDENTOPERATIONSSERVICE_QNAME);
    }

    public StudentOperationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTOPERATIONSSERVICE_QNAME, features);
    }

    public StudentOperationsService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTOPERATIONSSERVICE_QNAME);
    }

    public StudentOperationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTOPERATIONSSERVICE_QNAME, features);
    }

    public StudentOperationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentOperationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentOperations
     */
    @WebEndpoint(name = "StudentOperationsPort")
    public StudentOperations getStudentOperationsPort() {
        return super.getPort(new QName("http://server/", "StudentOperationsPort"), StudentOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentOperations
     */
    @WebEndpoint(name = "StudentOperationsPort")
    public StudentOperations getStudentOperationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "StudentOperationsPort"), StudentOperations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTOPERATIONSSERVICE_EXCEPTION!= null) {
            throw STUDENTOPERATIONSSERVICE_EXCEPTION;
        }
        return STUDENTOPERATIONSSERVICE_WSDL_LOCATION;
    }

}
